Repository dnd-side-project/dnd-8th-4-android, pull requests merged in 2023-02, with the labels that each got.

#2 #1 [전체] 컬러 및 폰트 세팅
  .idea/gradle.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#4 #3 [메인홈] 상단 레이아웃 생성
  .idea/misc.xml
  app/src/main/java/com/dnd_8th_4_android/wery/MainActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/GroupFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/MissionFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/res/color/selector_bottom_navigation_icon.xml
  app/src/main/res/drawable/ic_group.xml
  app/src/main/res/drawable/ic_group_create.xml
  app/src/main/res/drawable/ic_main.xml
  app/src/main/res/drawable/ic_mission.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_close.xml
  app/src/main/res/drawable/shape_f6f7f9_radius_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#7 #6 [스플래쉬] 이동 로직 구현
  .github/pull_request_template.md
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/WeRyApplication.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/local/AuthLocalDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/model/SplashType.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/OnboardingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_splash.xml
Labels: 📩 pull request

#10 #5 가입된 그룹이 없을 시 레이아웃 생성
  .idea/misc.xml
  app/src/main/res/drawable-hdpi/bg_crying_face.png
  app/src/main/res/drawable-hdpi/bg_no_group.png
  app/src/main/res/drawable-xhdpi/bg_crying_face.png
  app/src/main/res/drawable-xhdpi/bg_no_group.png
  app/src/main/res/drawable-xxhdpi/bg_crying_face.png
  app/src/main/res/drawable-xxhdpi/bg_no_group.png
  app/src/main/res/drawable-xxxhdpi/bg_crying_face.png
  app/src/main/res/drawable-xxxhdpi/bg_no_group.png
  app/src/main/res/drawable/shape_f6f7f9_radius_8.xml
  app/src/main/res/layout/activity_no_group.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#12 #11 [메인홈] 가입된 그룹이 있을 시 레이아웃 생성
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_clip.xml
  app/src/main/res/drawable/ic_modify.xml
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_remove.xml
  app/src/main/res/drawable/inset_ffffff_radius_10_16.xml
  app/src/main/res/drawable/shape_e0e2e5_radius_4.xml
  app/src/main/res/drawable/shape_ffffff_radius_10.xml
  app/src/main/res/layout/activity_group.xml
  app/src/main/res/layout/bottom_sheet_fragment_popup.xml
  app/src/main/res/layout/dialog_fragment_remove.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#14 #13 [메인홈] 그룹 리스트 생성
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponseGroupData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/GroupRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/MarginItemDecoration.kt
  app/src/main/res/drawable/ic_all_my_group.xml
  app/src/main/res/drawable/selector_btn_all_my_group.xml
  app/src/main/res/drawable/selector_btn_group.xml
  app/src/main/res/drawable/shape_f0f1f3_radius_16_black_1_5.xml
  app/src/main/res/drawable/shape_f0f1f3_radius_16_f6f7f9.xml
  app/src/main/res/drawable/shape_ffffff_radius_16_black_1_5.xml
  app/src/main/res/drawable/shape_ffffff_radius_16_e0e2e5.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_all_my_group.xml
  app/src/main/res/layout/item_my_group.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat, 🎨 style

#17 #15 [온보딩] 온보딩 로직 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/local/AuthLocalDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/base/BaseActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/OnboardingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/adapter/OnBoardingAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/view/OnBoardingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/item_onboard.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#19 #18 [로그인] 로그인 레이아웃 생성
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-hdpi/img_checkbox_checked.png
  app/src/main/res/drawable-hdpi/img_checkbox_default.png
  app/src/main/res/drawable-mdpi/img_checkbox_checked.png
  app/src/main/res/drawable-mdpi/img_checkbox_default.png
  app/src/main/res/drawable-xhdpi/img_checkbox_checked.png
  app/src/main/res/drawable-xhdpi/img_checkbox_default.png
  app/src/main/res/drawable-xxhdpi/img_checkbox_checked.png
  app/src/main/res/drawable-xxhdpi/img_checkbox_default.png
  app/src/main/res/drawable-xxxhdpi/img_checkbox_checked.png
  app/src/main/res/drawable-xxxhdpi/img_checkbox_default.png
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_blind_off.xml
  app/src/main/res/drawable/ic_blind_on.xml
  app/src/main/res/drawable/selector_btn.xml
  app/src/main/res/drawable/selector_checkbox.xml
  app/src/main/res/drawable/shape_black_radius_8.xml
  app/src/main/res/drawable/shape_ffffff_radius_8_e0e2e5.xml
  app/src/main/res/drawable/shape_gray300_radius_8.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/dialog_fragment_remove.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#21 #20 [로그인] 로그인 로직 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/BaseResponse.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/sign/ResponseSignInData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/view/OnBoardingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignInActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignInViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/selector_blind.xml
  app/src/main/res/drawable/shape_white_radius_8_black.xml
  app/src/main/res/layout/activity_sign_in.xml
Labels: 📩 pull request

#22 #16 [메인홈] 피드 리스트 생성
  .idea/misc.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponsePostData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/base/BaseBottomDialogFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/base/BaseDialogFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostImageAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/PopupBottomDialogDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/PostRemoveDialog.kt
  app/src/main/res/drawable/bottom_sheet_dialog_24.xml
  app/src/main/res/drawable/ic_comment_write.xml
  app/src/main/res/drawable/ic_dots_three_vertical.xml
  app/src/main/res/drawable/ic_emotion.xml
  app/src/main/res/drawable/shape_80000000_radius_20.xml
  app/src/main/res/drawable/shape_e0e2e5_oval.xml
  app/src/main/res/drawable/shape_f0f1f3_oval_f6f7f9.xml
  app/src/main/res/layout/activity_group.xml
  app/src/main/res/layout/bottom_dialog_popup.xml
  app/src/main/res/layout/bottom_sheet_fragment_popup.xml
  app/src/main/res/layout/dialog_fragment_remove.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/item_post_image.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#25 #24 [로그인] 로그인 이동로직 구현
  app/src/main/java/com/dnd_8th_4_android/wery/domain/model/DialogInfo.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignInActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignInViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/DialogFragmentUtil.kt
  app/src/main/res/layout/dialog_fragment.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#27 #26 [글쓰기] 글쓰기 레이아웃 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/view/WritingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/view/adapter/UploadPhotoAdapter.kt
  app/src/main/res/color/selector_txt.xml
  app/src/main/res/drawable-hdpi/img_photo_delete.png
  app/src/main/res/drawable-mdpi/img_photo_delete.png
  app/src/main/res/drawable-xhdpi/img_photo_delete.png
  app/src/main/res/drawable-xxhdpi/img_photo_delete.png
  app/src/main/res/drawable-xxxhdpi/img_photo_delete.png
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_expand_more.xml
  app/src/main/res/drawable/ic_expandless.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/shape_photo.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_writing.xml
  app/src/main/res/layout/item_writing_photo.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#29 #28 [글쓰기] 이미지 업로드 로직 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/base/BaseActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/adapter/UploadPhotoAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/view/WritingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/viewmodel/WritingViewModel.kt
  app/src/main/res/drawable/selector_blind.xml
  app/src/main/res/drawable/shape_photo.xml
  app/src/main/res/layout/activity_writing.xml
  app/src/main/res/layout/item_writing_photo.xml
Labels: 📩 pull request

#32 #31 [회원가입] 회원가입 레이아웃 생성
  .idea/misc.xml
  app/src/main/res/drawable/et_sign_up_normal.xml
  app/src/main/res/drawable/et_sign_up_selected.xml
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/selector_et_sign_up.xml
  app/src/main/res/layout/fragment_sign_up_email.xml
  app/src/main/res/layout/fragment_sign_up_name.xml
  app/src/main/res/layout/fragment_sign_up_nickname.xml
  app/src/main/res/layout/fragment_sign_up_password.xml
  app/src/main/res/layout/fragment_sign_up_use_agreement.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#34 #30 [글쓰기] 장소 검색 서버 통신 구현
  .idea/discord.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/PlaceService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/datasource/PlaceRemoteDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/write/ResponseSearchPlace.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/PlaceRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/di/RetrofitModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/PlaceRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/place/adapter/SearchAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/place/view/SearchPlaceActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/place/viewmodel/SearchPlaceViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/adapter/UploadPhotoAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/WritingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/viewmodel/WritingViewModel.kt
  app/src/main/res/color/selector_edittext_search.xml
  app/src/main/res/color/selector_layout_search.xml
  app/src/main/res/layout/activity_search_place.xml
  app/src/main/res/layout/activity_writing.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 📩 pull request

#36 #33 [회원가입] 회원가입 로직 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/sign/RequestSignUpData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/sign/ResponseSignUpData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/MainActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/view/OnBoardingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignInFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignUpEmailFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignUpNameFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignUpNicknameFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignUpPasswordFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignUpUseAgreementFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignUpEmailViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignUpNameViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignUpNicknameViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignUpPasswordViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignUpUseAgreementViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/selector_checkbox.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/fragment_sign_up_email.xml
  app/src/main/res/layout/fragment_sign_up_name.xml
  app/src/main/res/layout/fragment_sign_up_nickname.xml
  app/src/main/res/layout/fragment_sign_up_password.xml
  app/src/main/res/layout/fragment_sign_up_use_agreement.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/sign_navigation.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#38 #35 [글쓰기] 글쓰기 활성화 로직 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/datasource/PlaceRemoteDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/datasource/PlaceRemoteDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/write/ResponseGroupList.kt
  app/src/main/java/com/dnd_8th_4_android/wery/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/place/adapter/SearchAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/place/view/SearchPlaceActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/place/viewmodel/SearchPlaceViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/adapter/SelectGroupAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/SelectGroupBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/WritingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/viewmodel/WritingViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/BindingAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/ViewExt.kt
  app/src/main/res/color/selector_layout_search.xml
  app/src/main/res/layout/activity_writing.xml
  app/src/main/res/layout/dialog_fragment_select_group.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/item_select_group.xml
Labels: 📩 pull request

#40 #39 [글쓰기] 세부 이벤트 조정
  app/src/main/java/com/dnd_8th_4_android/wery/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/SelectGroupBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/WritingActivity.kt
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#44 #43 [글 상세보기] 글 상세보기 레이아웃 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailCommentData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailCommentImageData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailCommentNoImageData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailEmotionData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailImageData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailStickerData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailCommentRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailEmotionRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailImageRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailStickerRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/view/PostDetailActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/GroupRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/PopupBottomDialogDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/PostRemoveDialog.kt
  app/src/main/res/drawable/ic_back_white.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_oval_plus.xml
  app/src/main/res/drawable/ic_smile.xml
  app/src/main/res/drawable/ic_sticker.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/item_post_detail_comment.xml
  app/src/main/res/layout/item_post_detail_comment_image.xml
  app/src/main/res/layout/item_post_detail_emotion.xml
  app/src/main/res/layout/item_post_detail_emotion_plus.xml
  app/src/main/res/layout/item_post_detail_image.xml
  app/src/main/res/layout/item_post_detail_sticker.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#46 #45 [글 상세보기] 글 상세보기 로직 구현
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailEmotionData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailImageData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponsePostData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/model/PopupWindowType.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailCommentRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailEmotionRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailStickerRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/view/PostDetailActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/viewmodel/PostDetailViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/res/drawable/ic_send_off.xml
  app/src/main/res/drawable/ic_send_on.xml
  app/src/main/res/drawable/ic_sticker_off.xml
  app/src/main/res/drawable/ic_sticker_on.xml
  app/src/main/res/drawable/selector_send.xml
  app/src/main/res/drawable/selector_sticker.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/item_post_detail_emotion_plus.xml
  app/src/main/res/values/dimens.xml
  settings.gradle
Labels: 📩 pull request

#50 #49 [모아보기] 카카오 지도 sdk 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignInFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/place/view/SearchPlaceActivity.kt
  app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  app/src/main/jniLibs/libDaumMapEngineApi.so
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_sign_in.xml
Labels: 📩 pull request

#52 #51 [글쓰기] 디자인 변경사항 반영
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/res/color/selector_layout_search.xml
  app/src/main/res/layout/activity_search_place.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: 📩 pull request

#58 #57 [모아보기] 모아보기 레이아웃 생성
  app/src/main/res/drawable-hdpi/bg_mission_blue.png
  app/src/main/res/drawable-hdpi/bg_mission_green.png
  app/src/main/res/drawable-hdpi/bg_mission_pink.png
  app/src/main/res/drawable-hdpi/bg_post_preview.png
  app/src/main/res/drawable-mdpi/bg_mission_blue.png
  app/src/main/res/drawable-mdpi/bg_mission_green.png
  app/src/main/res/drawable-mdpi/bg_mission_pink.png
  app/src/main/res/drawable-mdpi/bg_post_preview.png
  app/src/main/res/drawable-xhdpi/bg_mission_blue.png
  app/src/main/res/drawable-xhdpi/bg_mission_green.png
  app/src/main/res/drawable-xhdpi/bg_mission_pink.png
  app/src/main/res/drawable-xhdpi/bg_post_preview.png
  app/src/main/res/drawable-xxhdpi/bg_mission_blue.png
  app/src/main/res/drawable-xxhdpi/bg_mission_green.png
  app/src/main/res/drawable-xxhdpi/bg_mission_pink.png
  app/src/main/res/drawable-xxhdpi/bg_post_preview.png
  app/src/main/res/drawable-xxxhdpi/bg_mission_blue.png
  app/src/main/res/drawable-xxxhdpi/bg_mission_green.png
  app/src/main/res/drawable-xxxhdpi/bg_mission_pink.png
  app/src/main/res/drawable-xxxhdpi/bg_post_preview.png
  app/src/main/res/drawable/ic_dot.xml
  app/src/main/res/drawable/shap_33black_radius_4.xml
  app/src/main/res/drawable/shape_oval_b3000000.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_map_mission.xml
  app/src/main/res/layout/item_map_post.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#60 #47 [그룹별 메인] 그룹별 메인 레이아웃 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/group/ResponseAccessGroupData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/view/PostDetailActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/adapter/AccessGroupMissionRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/adapter/GroupListRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/view/AccessGroupFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/viewmodel/AccessGroupViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/res/drawable-hdpi/img_fire.png
  app/src/main/res/drawable-hdpi/img_sample.png
  app/src/main/res/drawable-mdpi/img_fire.png
  app/src/main/res/drawable-mdpi/img_sample.png
  app/src/main/res/drawable-xhdpi/img_fire.png
  app/src/main/res/drawable-xhdpi/img_sample.png
  app/src/main/res/drawable-xxhdpi/img_fire.png
  app/src/main/res/drawable-xxhdpi/img_sample.png
  app/src/main/res/drawable-xxxhdpi/img_fire.png
  app/src/main/res/drawable-xxxhdpi/img_sample.png
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_check_write.xml
  app/src/main/res/drawable/ic_invite.xml
  app/src/main/res/drawable/ic_next_white.xml
  app/src/main/res/drawable/ic_oval_plus_18.xml
  app/src/main/res/drawable/ic_search_24.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/shape_33black_radius_4.xml
  app/src/main/res/layout/activity_no_mission.xml
  app/src/main/res/layout/activity_yes_mission.xml
  app/src/main/res/layout/fragment_access_group.xml
  app/src/main/res/layout/item_group_list.xml
  app/src/main/res/layout/item_yes_mission.xml
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#62 #59 [로그인] 로그인 서버 통신 구현
  app/src/main/java/com/dnd_8th_4_android/wery/WeRyApplication.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/XAccessTokenInterceptor.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/sign/ResponseSignInData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/AppModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/NetWorkModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignInFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignInViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/splash/SplashActivity.kt
Labels: 📩 pull request

#64 #61 [회원가입] 회원가입 서버 통신 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/SignUpService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/SignUpDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/SignUpDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/sign/RequestSignUpData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/sign/ResponseSignUpData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/SignUpRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/SignUpRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/ApiModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignUpNicknameFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/viewmodel/SignUpNicknameViewModel.kt
  app/src/main/res/layout/fragment_sign_up_nickname.xml
  app/src/main/res/navigation/sign_navigation.xml
Labels: 📩 pull request

#67 #65 [메인홈] 사용자 가입한 그룹 목록 조회
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/HomeService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/HomeDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/HomeDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponseGroupData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/HomeRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/ApiModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/adapter/GroupBookmarkRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/view/GroupFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/viewmodel/GroupViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/GroupRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/viewmodel/HomeViewModel.kt
Labels: 📩 pull request

#69 #63 [모아보기] 카카오 지도 세팅
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MarkerEventListener.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/MissionFragment.kt
  app/src/main/res/layout/fragment_mission.xml
Labels: 📩 pull request

#70 #68 [메인 홈] 메인 홈 서버 통신 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/HomeService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/HomeDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/HomeDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/RequestEmotionStatus.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponseEmotionData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponseGroupData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponsePostData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/HomeRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/view/AccessGroupFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/GroupRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostImageAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/item_my_group.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#72 #63 [모아보기] 지도 클릭 이벤트 세팅
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapFeedBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapMissionBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MarkerEventListener.kt
  app/src/main/res/drawable-hdpi/bg_mission_blue.png
  app/src/main/res/drawable-hdpi/bg_mission_green.png
  app/src/main/res/drawable-hdpi/bg_mission_pink.png
  app/src/main/res/drawable-hdpi/bg_post_preview.png
  app/src/main/res/drawable-mdpi/bg_mission_blue.png
  app/src/main/res/drawable-mdpi/bg_mission_green.png
  app/src/main/res/drawable-mdpi/bg_mission_pink.png
  app/src/main/res/drawable-mdpi/bg_post_preview.png
  app/src/main/res/drawable-xhdpi/bg_mission_blue.png
  app/src/main/res/drawable-xhdpi/bg_mission_green.png
  app/src/main/res/drawable-xhdpi/bg_mission_pink.png
  app/src/main/res/drawable-xhdpi/bg_post_preview.png
  app/src/main/res/drawable-xxhdpi/bg_mission_blue.png
  app/src/main/res/drawable-xxhdpi/bg_mission_green.png
  app/src/main/res/drawable-xxhdpi/bg_mission_pink.png
  app/src/main/res/drawable-xxhdpi/bg_post_preview.png
  app/src/main/res/drawable-xxxhdpi/bg_mission_blue.png
  app/src/main/res/drawable-xxxhdpi/bg_mission_green.png
  app/src/main/res/drawable-xxxhdpi/bg_mission_pink.png
  app/src/main/res/drawable-xxxhdpi/bg_post_preview.png
  app/src/main/res/drawable/ic_feed_default.xml
  app/src/main/res/drawable/ic_feed_select.xml
  app/src/main/res/drawable/ic_mission_default.xml
  app/src/main/res/drawable/ic_mission_select.xml
  app/src/main/res/drawable/selector_filter_bottom.xml
  app/src/main/res/drawable/selector_filter_feed.xml
  app/src/main/res/drawable/selector_filter_mission.xml
  app/src/main/res/drawable/selector_filter_top.xml
  app/src/main/res/drawable/shape_black_radius_30.xml
  app/src/main/res/drawable/shape_blue_radius_8.xml
  app/src/main/res/drawable/shape_gray200_radius_12.xml
  app/src/main/res/drawable/shape_green_radius_8.xml
  app/src/main/res/drawable/shape_pink_bottom_radius_8.xml
  app/src/main/res/drawable/shape_pink_radius_8.xml
  app/src/main/res/drawable/shape_pink_top_radius_8.xml
  app/src/main/res/drawable/shape_white_bottom_radius_8.xml
  app/src/main/res/drawable/shape_white_radius_8.xml
  app/src/main/res/drawable/shape_white_top_radius_8.xml
  app/src/main/res/layout/dialog_map_mission.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_map_mission.xml
  app/src/main/res/layout/item_map_post.xml
  app/src/main/res/layout/item_marker.xml
  app/src/main/res/layout/item_marker_feed.xml
Labels: 📩 pull request

#74 #73 [모아보기] 피드 마커 선택 이벤트
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/map/ResponseMapFeed.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/map/ResponseMapMission.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapFeedBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapMissionBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/adapter/MapFeedAdapter.kt
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_map_feed.xml
  app/src/main/res/layout/item_marker_feed.xml
  app/src/main/res/values/dimens.xml
Labels: 📩 pull request

#76 #75 [모아보기] 검색 결과 좌표 입력 이벤트
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/WritingActivity.kt
  app/src/main/res/layout/fragment_map.xml
Labels: 📩 pull request

#79 #71 [글 상세보기] 글 상세보기 서버 통신 구현
  .idea/misc.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/DetailService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/DetailDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/DetailDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/RequestPostDetailCommentNote.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailCommentData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailCommentImageData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailCommentNoImageData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailEmotionData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponsePostData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/DetailRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/ApiModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailCommentRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailEmotionRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailImageRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/view/PostDetailActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/viewmodel/PostDetailViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/item_post_detail_emotion.xml
Labels: 📩 pull request

#80 #78 [미션] 미션 메인 레이아웃 생성
  app/build.gradle
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/MissionFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/MissionViewModel.kt
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_filter_remain.xml
  app/src/main/res/drawable/ic_mission_certify.xml
  app/src/main/res/drawable/ic_mission_recommend_add.xml
  app/src/main/res/drawable/ic_mission_write.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/layout/fragment_my_mission.xml
  app/src/main/res/layout/framgent_mission_progress.xml
  app/src/main/res/layout/item_mission_card.xml
  app/src/main/res/layout/item_mission_exist.xml
  app/src/main/res/layout/item_mission_no_exist.xml
  app/src/main/res/layout/item_mission_recommend.xml
  app/src/main/res/layout/item_mission_waiting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#82 #81 [미션] 미션 탭 오류 수정
  app/build.gradle
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/MissionFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/mymission/view/MyMissionFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/sticker/StickerFragment.kt
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/layout/fragment_sticker.xml
  app/src/main/res/layout/framgent_mission_progress.xml
Labels: 🐛 fix, 📩 pull request

#85 #84 [미션] 미션 생성 레이아웃 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/create/CreateMissionActivity.kt
  app/src/main/res/drawable-hdpi/img_mission_color_blue.png
  app/src/main/res/drawable-hdpi/img_mission_color_blue_checked.png
  app/src/main/res/drawable-hdpi/img_mission_color_green.png
  app/src/main/res/drawable-hdpi/img_mission_color_green_checked.png
  app/src/main/res/drawable-hdpi/img_mission_color_pink.png
  app/src/main/res/drawable-hdpi/img_mission_color_pink_checked.png
  app/src/main/res/drawable-mdpi/img_mission_color_blue.png
  app/src/main/res/drawable-mdpi/img_mission_color_blue_checked.png
  app/src/main/res/drawable-mdpi/img_mission_color_green.png
  app/src/main/res/drawable-mdpi/img_mission_color_green_checked.png
  app/src/main/res/drawable-mdpi/img_mission_color_pink.png
  app/src/main/res/drawable-mdpi/img_mission_color_pink_checked.png
  app/src/main/res/drawable-xhdpi/img_mission_color_blue.png
  app/src/main/res/drawable-xhdpi/img_mission_color_blue_checked.png
  app/src/main/res/drawable-xhdpi/img_mission_color_green.png
  app/src/main/res/drawable-xhdpi/img_mission_color_green_checked.png
  app/src/main/res/drawable-xhdpi/img_mission_color_pink.png
  app/src/main/res/drawable-xhdpi/img_mission_color_pink_checked.png
  app/src/main/res/drawable-xxhdpi/img_mission_color_blue.png
  app/src/main/res/drawable-xxhdpi/img_mission_color_blue_checked.png
  app/src/main/res/drawable-xxhdpi/img_mission_color_green.png
  app/src/main/res/drawable-xxhdpi/img_mission_color_green_checked.png
  app/src/main/res/drawable-xxhdpi/img_mission_color_pink.png
  app/src/main/res/drawable-xxhdpi/img_mission_color_pink_checked.png
  app/src/main/res/drawable-xxxhdpi/img_mission_color_blue.png
  app/src/main/res/drawable-xxxhdpi/img_mission_color_blue_checked.png
  app/src/main/res/drawable-xxxhdpi/img_mission_color_green.png
  app/src/main/res/drawable-xxxhdpi/img_mission_color_green_checked.png
  app/src/main/res/drawable-xxxhdpi/img_mission_color_pink.png
  app/src/main/res/drawable-xxxhdpi/img_mission_color_pink_checked.png
  app/src/main/res/drawable/selector_mission_color_blue.xml
  app/src/main/res/drawable/selector_mission_color_green.xml
  app/src/main/res/drawable/selector_mission_color_pink.xml
  app/src/main/res/drawable/selector_mission_tab.xml
  app/src/main/res/drawable/shape_gray50_radius_8_gray300.xml
  app/src/main/res/drawable/shape_white_radius_8_f47aff.xml
  app/src/main/res/layout/activity_create_mission.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#88 #86 [미션] 미션 생성 로직 구현
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/create/CreateMissionActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/create/CreateMissionViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/SelectGroupBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/WritingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/UtilExt.kt
  app/src/main/res/layout/activity_create_mission.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat

#90 #89 [미션] 스티커 탭 관련 레이아웃 생성
  app/src/main/res/drawable/ic_speech_down.xml
  app/src/main/res/drawable/ic_sticker_lock.xml
  app/src/main/res/drawable/img_sticker_temp_default.png
  app/src/main/res/drawable/img_sticker_temp_selected.png
  app/src/main/res/drawable/progress_drawable.xml
  app/src/main/res/drawable/shape_black50_radius_8.xml
  app/src/main/res/drawable/shape_black_radius_4.xml
  app/src/main/res/drawable/shape_white_radius_100_pink.xml
  app/src/main/res/layout/activity_sticker_info.xml
  app/src/main/res/layout/dialog_fragment_sticker_info.xml
  app/src/main/res/layout/fragment_sticker.xml
  app/src/main/res/layout/item_sticker.xml
  app/src/main/res/layout/item_sticker_each.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#92 #87 [검색 화면] 검색 화면 생성
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/DetailService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/HomeService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/SearchService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/DetailDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/DetailDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/HomeDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/HomeDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/SearchDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/SearchDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/detail/ResponsePostDetailData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/search/ResponsePostSearchData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/DetailRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/HomeRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/SearchRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/ApiModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/adapter/PostDetailImageRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/view/PostDetailActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/detail/viewmodel/PostDetailViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/search/adapter/PostSearchAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/search/view/SearchPostActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/search/viewmodel/SearchPostViewModel.kt
  app/src/main/res/drawable/shape_post_count.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_post_detail_image.xml
  app/src/main/res/layout/item_post_search.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#94 #93 [그룹 메인] 그룹 메인 서버 통신 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/GroupService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/GroupDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/GroupDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/group/ResponseBookmarkData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/group/ResponseGroupListData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/group/ResponseSetBookmarkData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponseGroupData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/GroupRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/GroupRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/ApiModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/adapter/GroupBookmarkRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/adapter/GroupListRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/view/GroupFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/viewmodel/GroupViewModel.kt
  app/src/main/res/layout/fragment_group.xml
Labels: 📩 pull request

#96 #91 [메인] 스티커 화면 이동 로직 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/mission/ResponseSticker.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/MissionFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/sticker/StickerFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/sticker/adapter/StickerAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/sticker/adapter/StickerDetailAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/sticker/view/StickerDetailActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/sticker/view/StickerFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/sticker/view/StickerInfoBottomDialog.kt
  app/src/main/res/drawable/shape_gray100_radius_8_gray200.xml
  app/src/main/res/layout/activity_sticker_detail.xml
  app/src/main/res/layout/activity_sticker_info.xml
  app/src/main/res/layout/dialog_fragment_sticker_info.xml
  app/src/main/res/layout/fragment_sticker.xml
  app/src/main/res/layout/item_sticker.xml
  app/src/main/res/layout/item_sticker_detail.xml
  app/src/main/res/layout/item_sticker_each.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#98 #97 [미션] 미션 상세보기 레이아웃 생성
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/view/MissionDetailActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/view/MissionFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/viewmodel/MissionViewModel.kt
  app/src/main/res/layout/activity_mission_detail.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/navigation/home_navigation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#100 #95 [그룹 진입 화면] 그룹 진입 화면 서버 통신 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/GroupService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/GroupDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/GroupDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/group/ResponseGroupMissionData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/home/ResponsePostData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/GroupRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/model/MissionColor.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/GroupRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/adapter/AccessGroupMissionRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/adapter/GroupListRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/view/AccessGroupFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/view/GroupFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/viewmodel/AccessGroupViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/viewmodel/GroupViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/adapter/PostRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/res/drawable/ic_bookmark_star_24_off.xml
  app/src/main/res/drawable/ic_bookmark_star_24_on.xml
  app/src/main/res/drawable/selector_bookmark_star_24.xml
  app/src/main/res/layout/fragment_access_group.xml
  app/src/main/res/layout/item_my_group.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/item_yes_mission.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#101 #99 [글쓰기] 글쓰기 서버 작업 api 수정 대기
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/PostService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/PostDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/PostDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/write/ResponseGroupList.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/PostRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/PostRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/ApiModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/adapter/SelectGroupAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/adapter/UploadPhotoAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/SelectGroupBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/WritingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/viewmodel/WritingViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/MultiPartFileUtil.kt
  app/src/main/res/layout/item_select_group.xml
Labels: 📩 pull request

#104 #102 [전체] 담당화면 디자인 asset 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/domain/model/OnBoardData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/create/view/CreateGroupActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/adapter/OnBoardingAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/onboard/view/OnBoardingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/sign/view/SignInFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-hdpi/img_group_default.png
  app/src/main/res/drawable-hdpi/img_onboard_four.png
  app/src/main/res/drawable-hdpi/img_onboard_one.png
  app/src/main/res/drawable-hdpi/img_onboard_three.png
  app/src/main/res/drawable-hdpi/img_onboard_two.png
  app/src/main/res/drawable-hdpi/img_splash.png
  app/src/main/res/drawable-mdpi/img_group_default.png
  app/src/main/res/drawable-mdpi/img_onboard_four.png
  app/src/main/res/drawable-mdpi/img_onboard_one.png
  app/src/main/res/drawable-mdpi/img_onboard_three.png
  app/src/main/res/drawable-mdpi/img_onboard_two.png
  app/src/main/res/drawable-mdpi/img_splash.png
  app/src/main/res/drawable-xhdpi/img_group_default.png
  app/src/main/res/drawable-xhdpi/img_onboard_four.png
  app/src/main/res/drawable-xhdpi/img_onboard_one.png
  app/src/main/res/drawable-xhdpi/img_onboard_three.png
  app/src/main/res/drawable-xhdpi/img_onboard_two.png
  app/src/main/res/drawable-xhdpi/img_splash.png
  app/src/main/res/drawable-xxhdpi/img_group_default.png
  app/src/main/res/drawable-xxhdpi/img_onboard_four.png
  app/src/main/res/drawable-xxhdpi/img_onboard_one.png
  app/src/main/res/drawable-xxhdpi/img_onboard_three.png
  app/src/main/res/drawable-xxhdpi/img_onboard_two.png
  app/src/main/res/drawable-xxhdpi/img_splash.png
  app/src/main/res/drawable-xxxhdpi/img_group_default.png
  app/src/main/res/drawable-xxxhdpi/img_onboard_four.png
  app/src/main/res/drawable-xxxhdpi/img_onboard_one.png
  app/src/main/res/drawable-xxxhdpi/img_onboard_three.png
  app/src/main/res/drawable-xxxhdpi/img_onboard_two.png
  app/src/main/res/drawable-xxxhdpi/img_splash.png
  app/src/main/res/drawable/gif_login.gif
  app/src/main/res/drawable/shap_33black_radius_4.xml
  app/src/main/res/drawable/shape_gray100_radius_40_gray200.xml
  app/src/main/res/drawable/shape_radius_40_gray200.xml
  app/src/main/res/layout/activity_create_group.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/layout/item_onboard.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 📩 pull request

#105 #99 [feat] 글쓰기 서버 통신 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/PostService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/PostDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/PostDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/PostRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/adapter/UploadPhotoAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/view/WritingActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/write/upload/viewmodel/WritingViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/MultiPartFileUtil.kt
Labels: 📩 pull request

#108 #106 [글쓰기] 글 수정 서버 통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/PlaceService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/PostService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/PlaceRemoteDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/PlaceRemoteDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/PostDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/PostDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/post/ResponseGroupList.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/post/ResponsePostData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/post/ResponseSearchPlace.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/PlaceRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/PostRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/PlaceRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/PostRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/map/MapViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/create/CreateMissionActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/place/adapter/SearchAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/place/view/SearchPlaceActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/place/viewmodel/SearchPlaceViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/upload/adapter/SelectGroupAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/upload/adapter/UploadPhotoAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/upload/view/SelectGroupBottomDialog.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/upload/view/UploadPostActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/upload/viewmodel/PostViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/MultiPartFileUtil.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/util/PopupBottomDialog.kt
  app/src/main/res/layout/activity_search_place.xml
  app/src/main/res/layout/activity_upload_post.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/item_select_group.xml
Labels: 📩 pull request

#111 #109 [알림창] 알림창 화면 생성
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/AlertService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/AlertDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/AlertDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/alert/ResponseAlertInviteData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/AlertRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/AlertRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/ApiModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/DataSourceModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/di/RepositoryModule.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/alert/adapter/AlertInviteRecyclerViewAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/alert/view/AlertPopupActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/alert/view/FragmentAlertInvite.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/alert/view/FragmentAlertNotification.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/alert/viewmodel/AlertInviteViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/view/GroupFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/home/view/HomeFragment.kt
  app/src/main/res/color/selector_button.xml
  app/src/main/res/color/selector_button_f47aff.xml
  app/src/main/res/color/selector_txt_white.xml
  app/src/main/res/drawable/img_alert_invite.xml
  app/src/main/res/drawable/img_alert_notification.xml
  app/src/main/res/layout/activity_alert_popup.xml
  app/src/main/res/layout/fragment_alert_invite.xml
  app/src/main/res/layout/fragment_alert_notification.xml
  app/src/main/res/layout/item_alert_invite.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 📩 pull request

#113 #112 [마이페이지] 마이페이지 레이아웃 생성
  .idea/misc.xml
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mypage/view/MyPageFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mypage/view/MyPageMissionActivity.kt
  app/src/main/res/drawable/ic_next_gray700.xml
  app/src/main/res/layout/activity_mypage_bookmark.xml
  app/src/main/res/layout/activity_mypage_comment.xml
  app/src/main/res/layout/activity_mypage_mission.xml
  app/src/main/res/layout/activity_mypage_post.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_mypage_mission.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: 📩 pull request

#114 #110 [그룹] 그룹 생성 및 수정 서버통신 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/GroupService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/GroupDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/GroupDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/GroupRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/GroupRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/create/view/CreateGroupActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/create/viewmodel/CreateGroupViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/group/view/GroupInformationActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/upload/viewmodel/PostViewModel.kt
  app/src/main/res/layout/activity_create_group.xml
Labels: 📩 pull request

#116 #115 [미션] 진행중인 미션 상세보기 조회 서버 통신 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/MissionService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/MissionDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/MissionDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/mission/ResponseMyMissionCard.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/MissionRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/MissionRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/mymission/adapter/MyMissionAdapter.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/mymission/view/MissionProgressActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/mymission/viewmodel/MissionProgressViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/view/MissionDetailActivity.kt
  app/src/main/res/layout/activity_mission_progress.xml
Labels: 📩 pull request

#120 #119 [미션] 미션 생성 서버 통신 구현
  app/src/main/java/com/dnd_8th_4_android/wery/data/api/MissionService.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/MissionDataSource.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/datasource/MissionDataSourceImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/remote/model/mission/RequestCreateMissionData.kt
  app/src/main/java/com/dnd_8th_4_android/wery/data/repository/MissionRepositoryImpl.kt
  app/src/main/java/com/dnd_8th_4_android/wery/domain/repository/MissionRepository.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/create/CreateMissionActivity.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/create/CreateMissionViewModel.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/mission/mymission/view/MyMissionFragment.kt
  app/src/main/java/com/dnd_8th_4_android/wery/presentation/ui/post/upload/view/SelectGroupBottomDialog.kt
  app/src/main/res/layout/activity_create_mission.xml
Labels: 📩 pull request
